/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_moziqi_app_project_NdkJniUtils */

#ifndef _Included_com_moziqi_app_project_NdkJniUtils
#define _Included_com_moziqi_app_project_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_moziqi_app_project_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moziqi_app_project_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif